workflows:
  ios-unsigned-ipa:
    name: iOS Unsigned IPA
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        IPA_NAME: "1browser-unsigned.ipa"
    scripts:
      - name: Build iOS and package unsigned IPA
        script: |
          set +e

          flutter clean
          flutter pub get

          flutter build ios --release --no-codesign

          BUILD_STATUS=$?

          set -e

          echo "Flutter exit code: $BUILD_STATUS"

          if [ ! -d "build/ios/iphoneos/Runner.app" ]; then
              echo "Runner.app was not generated."
              exit $BUILD_STATUS
          fi

          echo "Runner.app was successfully generated."

          rm -rf build/ios/unsigned
          rm -rf build/ios/ipa

          mkdir -p build/ios/unsigned/Payload
          mkdir -p build/ios/ipa

          cp -R build/ios/iphoneos/Runner.app \
                build/ios/unsigned/Payload/Runner.app

          cd build/ios/unsigned

          zip -r ../ipa/1browser-unsigned.ipa Payload
    artifacts:
      - build/ios/ipa/*.ipa
